name: 'PyInstaller Build'
description: 'build your python program to executable'
author: 'Eric Lam'
branding:
  icon: 'package'
  color: 'gray-dark'

inputs:
  main:
    description: 'the main python file (without .py)'
    required: true
  dist:
    description: 'the dist path'
    required: false
    default: './dist'
  python_version:
    description: 'the version of python'
    required: false
    default: '3.11.9'
  pyinstaller_version:
    description: 'the version of pyinstaller'
    required: false
    default: '6.8.0'
  artifact:
    description: 'the output exe name'
    required: false
    default: 'main'
  use-dependencies:
    description: 'whether to install requirements.txt before build'
    required: false
    default: true
  no-console:
    description: 'whether to disppear console terminal'
    required: false
    default: false
  icon:
    description: 'add the icon mark into your executable, the file path of your ico'
    required: false
    default: 'NONE'

runs:
  using: "composite"
  steps: 
    - name: setup python 3.11.9
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}
    - name: build exe with pyinstaller
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
