name: 'PyInstaller Build'
description: 'build your python program to executable'
author: 'Eric Lam'

inputs:
  main:
    description: 'the main python file (without .py)'
    required: true
  dist:
    description: 'the dist path'
    required: false
    default: './dist'
  python_version:
    description: 'the version of python'
    required: false
    default: '3.9.7'
  pyinstaller_version:
    description: 'the version of pyinstaller'
    required: false
    default: '4.7'
  artifact:
    description: 'the exe name'
    required: false
    default: ${{ inputs.main }}

runs:
  using: "composite"
  steps: 
    - name: setup python 3.9.7
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}
    - name: build exe with pyinstaller
      shell: bash
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        pip install pyinstaller==${{ inputs.pyinstaller_version }}
        pyinstaller --clean -y --dist ${{ inputs.dist }} --name ${{ inputs.artifact }} --onefile ${{ inputs.main }}.py
        chown -R --reference=. ./dist
