name: 'PyInstaller Build'
description: 'build your python program to executable'
author: 'Michael Ortiz'
branding:
  icon: 'package'
  color: 'gray-dark'

inputs:
  python-version:
    description: 'the version of python'
    required: false
    default: '3.11.9'
  spec-file:
    description: 'spec-file to build application'
    required: true
  
runs:
  using: "composite"
  steps: 
    - name: setup python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: build exe with pyinstaller
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install --no-root
        python -m pyinstaller ${{ inputs.spec-file }} -y
